// Generated by regen_corpus.mjs — do not edit by hand.

pub const CORPUS_VERSION: u32 = 1;

pub const Entry = struct {
    name: []const u8,
    path: []const u8,
};

pub const entries = [_]Entry{
    .{ .name = "wall-right-edge", .path = "tests/corpus/wall-right-edge.jsonl" },
    .{ .name = "wall-serpentine-death", .path = "tests/corpus/wall-serpentine-death.jsonl" },
    .{ .name = "win-full-board", .path = "tests/corpus/win-full-board.jsonl" },
    .{ .name = "wrap-serpentine", .path = "tests/corpus/wrap-serpentine.jsonl" },
};
