// Generated by regen_corpus.mjs — do not edit by hand.

pub const CORPUS_VERSION: u32 = 1;

pub const Entry = struct {
    name: []const u8,
    path: []const u8,
};

pub const entries = [_]Entry{
    .{ .name = "negative-wrap-y10-col9a", .path = "tests/corpus/negative-wrap-y10-col9a.jsonl" },
    .{ .name = "negative-wrap-y12-col9", .path = "tests/corpus/negative-wrap-y12-col9.jsonl" },
    .{ .name = "negative-wrap-y16-col15", .path = "tests/corpus/negative-wrap-y16-col15.jsonl" },
    .{ .name = "one-turn-per-tick", .path = "tests/corpus/one-turn-per-tick.jsonl" },
    .{ .name = "random-01", .path = "tests/corpus/random-01.jsonl" },
    .{ .name = "random-02", .path = "tests/corpus/random-02.jsonl" },
    .{ .name = "random-03", .path = "tests/corpus/random-03.jsonl" },
    .{ .name = "random-04", .path = "tests/corpus/random-04.jsonl" },
    .{ .name = "random-05", .path = "tests/corpus/random-05.jsonl" },
    .{ .name = "random-06", .path = "tests/corpus/random-06.jsonl" },
    .{ .name = "random-07", .path = "tests/corpus/random-07.jsonl" },
    .{ .name = "random-08", .path = "tests/corpus/random-08.jsonl" },
    .{ .name = "random-09", .path = "tests/corpus/random-09.jsonl" },
    .{ .name = "random-10", .path = "tests/corpus/random-10.jsonl" },
    .{ .name = "random-11", .path = "tests/corpus/random-11.jsonl" },
    .{ .name = "random-12", .path = "tests/corpus/random-12.jsonl" },
    .{ .name = "random-13", .path = "tests/corpus/random-13.jsonl" },
    .{ .name = "random-14", .path = "tests/corpus/random-14.jsonl" },
    .{ .name = "random-15", .path = "tests/corpus/random-15.jsonl" },
    .{ .name = "random-16", .path = "tests/corpus/random-16.jsonl" },
    .{ .name = "random-17", .path = "tests/corpus/random-17.jsonl" },
    .{ .name = "random-18", .path = "tests/corpus/random-18.jsonl" },
    .{ .name = "random-19", .path = "tests/corpus/random-19.jsonl" },
    .{ .name = "random-20", .path = "tests/corpus/random-20.jsonl" },
    .{ .name = "reject-180-down-then-up", .path = "tests/corpus/reject-180-down-then-up.jsonl" },
    .{ .name = "reject-180-opposite-then-perpendicular", .path = "tests/corpus/reject-180-opposite-then-perpendicular.jsonl" },
    .{ .name = "reject-180-right-then-left", .path = "tests/corpus/reject-180-right-then-left.jsonl" },
    .{ .name = "tail-blocked-by-middle-segment", .path = "tests/corpus/tail-blocked-by-middle-segment.jsonl" },
    .{ .name = "tail-chase-vacating-tail", .path = "tests/corpus/tail-chase-vacating-tail.jsonl" },
    .{ .name = "wall-corner-death", .path = "tests/corpus/wall-corner-death.jsonl" },
    .{ .name = "wall-right-edge", .path = "tests/corpus/wall-right-edge.jsonl" },
    .{ .name = "wall-right-edge16x16", .path = "tests/corpus/wall-right-edge16x16.jsonl" },
    .{ .name = "wall-serpentine-death", .path = "tests/corpus/wall-serpentine-death.jsonl" },
    .{ .name = "wall-top-edge-death10", .path = "tests/corpus/wall-top-edge-death10.jsonl" },
    .{ .name = "wall-turn-bottom-edge-death", .path = "tests/corpus/wall-turn-bottom-edge-death.jsonl" },
    .{ .name = "win-full-board", .path = "tests/corpus/win-full-board.jsonl" },
};
