//! Tier-B fuzz invariants (TASK-021): 256 committed seeds checked against
//! structural invariants, not the oracle checksum (docs/build-layout.md's
//! Tier-A/Tier-B split — Tier-A is single-behavior unit tests, Tier-B is
//! broad seed coverage). Unlike core/difftest.zig (TASK-020), there is no
//! oracle-recorded expectation to replay here: these are properties that
//! must hold for *any* legal sequence of inputs, so each is checked directly
//! against core/world.zig's own output rather than a recorded trace.
//!
//! Invariants 1-5 drive a single-player core/world.zig.World directly.
//! Invariant 6 needs more than one player moving in the same tick, which
//! core/world.zig does not model (it is deliberately single-player — see its
//! header comment); rather than build the full multiplayer ABI/lockstep
//! stack years ahead of TASK-023/TASK-053 (m-8), this file adds a minimal,
//! private, non-ABI two-player step primitive scoped only to prove
//! permutation invariance — see backlog/decisions/decision-020 for the exact
//! scope and why cross-player body collision is deliberately not modeled.
//!
//! The 256 seeds below are generated by a splitmix64 expansion of a single
//! fixed master constant (a one-time, deterministic codegen step, not a
//! runtime randomness source — see the task's implementation notes for the
//! generating script), the same "generated and independently re-derived,
//! not hand-computed" spirit as docs/rng.md's own test vectors.

const std = @import("std");
const rng = @import("rng");
const canon = @import("canon");
const world = @import("world");

const COLS = world.COLS;
const ROWS = world.ROWS;

/// Ticks driven per seed for invariants 1-5: enough to grow the snake
/// several times (exercising food placement and scoring) while keeping
/// 256 seeds' worth of test cheap to run on every `zig build test`.
const TICKS: u32 = 60;

pub const SEEDS = [_][4]u32{
    .{ 0x207168e4, 0x14239b84, 0x96f821a9, 0x7784a21b },
    .{ 0xe7b2bb56, 0xefb8a21b, 0x3cf54a40, 0x21b4fe12 },
    .{ 0xe7b8e9fb, 0x4bde4cfc, 0x15e17c76, 0xd8065a78 },
    .{ 0xe75460b2, 0xb96a0ccd, 0x498d985f, 0xd1ac4dc2 },
    .{ 0xa355997a, 0x9b85c988, 0x4a525aee, 0x4de06fde },
    .{ 0x849a6397, 0x6efc4276, 0x89f7d65b, 0x882186b2 },
    .{ 0x6f274043, 0xc7c68bf1, 0x7312f02e, 0xf2171ce7 },
    .{ 0x7ddd08b2, 0xa9943ac6, 0xdbf05334, 0x67fbf154 },
    .{ 0x042a32b5, 0xbf539aa0, 0x98ccb7a3, 0xd35b7301 },
    .{ 0xbb274a75, 0x3c6917cb, 0xfb848c3f, 0x4c8e094a },
    .{ 0xe9109ad7, 0x361d0a10, 0xeca1ca0f, 0x370f1a0b },
    .{ 0x25774002, 0x5e9c6826, 0xbd503db5, 0xb60b8125 },
    .{ 0x2cabaccb, 0x33e76e09, 0x680b9b2c, 0xbbc7ac00 },
    .{ 0x2b4a4372, 0x3aed8173, 0x4d338984, 0xa5463d24 },
    .{ 0x97c5de7d, 0xfee68228, 0xae33b9f5, 0xe8f14fd5 },
    .{ 0x9857df4c, 0x2f11a190, 0x70baf79b, 0xa0b8c8cf },
    .{ 0x6cce5d4f, 0xa687dac9, 0x110e0aab, 0x16dce417 },
    .{ 0x36679d03, 0x0bb61397, 0xd8a935da, 0x38f93685 },
    .{ 0x4e4a76bc, 0x60e4098c, 0xc5aa5d56, 0x72c6eaf2 },
    .{ 0x59121413, 0x434b8241, 0xe3ded050, 0x5982ab5e },
    .{ 0x4c3a9f0b, 0x876eec33, 0xc6d88efc, 0x96e332d9 },
    .{ 0xa7ee9181, 0x16ed7354, 0xb782f2d9, 0x2b13d6eb },
    .{ 0xaacd1608, 0x3cbd442a, 0x5c139c74, 0xef10070d },
    .{ 0x7dafaa43, 0x37a6a584, 0xa9774960, 0xe871bff5 },
    .{ 0x9e94d420, 0xa6cd2682, 0x6d6ec7a7, 0xb7f0342a },
    .{ 0xb4fd3ada, 0x2f9ea94a, 0xdf61d57b, 0x6b050651 },
    .{ 0x1782e69b, 0xdc1f47e0, 0x24b8dac4, 0xe3f42a4b },
    .{ 0x7530d14c, 0xeceefcc9, 0x98840ea9, 0x661034a4 },
    .{ 0x8eb4061b, 0x35c3b68e, 0x67276b17, 0xee05bfbd },
    .{ 0x55f24395, 0x437466ed, 0x5b57124f, 0x32986d92 },
    .{ 0xd883ce00, 0x40bce49d, 0x3883332a, 0x2d566303 },
    .{ 0x1fe8b629, 0x0544fa30, 0x7897e334, 0x4a1e3352 },
    .{ 0x4394a36b, 0x63576a90, 0x42b6ea08, 0xc0bf993a },
    .{ 0xc172db4e, 0xd6580cd3, 0x05d1b26c, 0x2a0dde41 },
    .{ 0xe2bfd749, 0xe6b4e20b, 0x330dd78d, 0x5b05222e },
    .{ 0x1d33f2cd, 0x1d6c1c20, 0xd72ad1fa, 0xa22cacad },
    .{ 0xf8e30061, 0x4f7f5575, 0xcc785661, 0x26437034 },
    .{ 0xf4d0f68c, 0x950943cd, 0xbc390111, 0xd81b3c8f },
    .{ 0xae03a05c, 0x33a33e00, 0x40d2d3da, 0x209c9315 },
    .{ 0x8f26bfb0, 0x57c0fd9d, 0xfb55d4a5, 0x94aa52e4 },
    .{ 0x729338fb, 0x69940f48, 0xf7c1f5bb, 0x21626094 },
    .{ 0x428128ba, 0xe4a72462, 0x2ba8d600, 0xb10997a8 },
    .{ 0x50bbbada, 0x45ec729c, 0x63457eda, 0xdce4b8a1 },
    .{ 0xcb949135, 0x652a732e, 0xaefa7499, 0x7729a739 },
    .{ 0xe0632b67, 0xedea8390, 0x2723a8e1, 0x0bfbad80 },
    .{ 0x72036028, 0xd4677bc4, 0xe8aa1d0a, 0x71ff8609 },
    .{ 0x7df56926, 0x630c72d0, 0x5679bb08, 0x84294bf6 },
    .{ 0x2b873ba9, 0x4dce28aa, 0xca18c7e1, 0x900a7add },
    .{ 0x4b1ce6db, 0x25911ae2, 0x4d11f5c3, 0x962d6a02 },
    .{ 0xa8030585, 0xf48b75bb, 0xbba1bf0f, 0xb6962ea3 },
    .{ 0xc1ea80a0, 0x437a3f76, 0xdf84314e, 0xe4e2b264 },
    .{ 0x33a5d427, 0xc1fb651a, 0x3d263638, 0x9a8abadd },
    .{ 0x20039fe2, 0x4a999787, 0x29b7125b, 0xfa97341e },
    .{ 0x011e4624, 0xa85fbf97, 0x6e19e744, 0xbbc422cc },
    .{ 0x7b5d71db, 0x223e67cb, 0x69f89b2e, 0x0da3b186 },
    .{ 0x61d9c378, 0x4a7546cc, 0x7e39646a, 0x9d030be2 },
    .{ 0xf08b6d1f, 0xed9be50f, 0xc95ff4da, 0x983ae95f },
    .{ 0xb89187c1, 0xa7b5c357, 0x3f440e54, 0x5ad6a42d },
    .{ 0x8d5f529b, 0x8a5a580c, 0x304b0ae5, 0xa4758c43 },
    .{ 0x3666c058, 0x1c85a3da, 0x2efaad79, 0x7bae0d42 },
    .{ 0x5244bd49, 0x1058d00d, 0xff87a2da, 0x148cd029 },
    .{ 0xbfebec0b, 0xfc80c47d, 0x9d937bfd, 0xa0ecec8e },
    .{ 0xf4f25a41, 0xa549a1e1, 0x2bc37f8f, 0x3ebfab35 },
    .{ 0x87068548, 0xa8481c70, 0x20e8de60, 0x57adce5a },
    .{ 0x9349c83e, 0x20389d71, 0x7bbb4195, 0x940fcddd },
    .{ 0x0c185317, 0x9748942d, 0x800c409a, 0x36769777 },
    .{ 0xa0a9b8e0, 0x6638d3f3, 0x13d23a5a, 0x29068b1a },
    .{ 0xc39691ab, 0x797e7dc7, 0x2e9b9c5c, 0x0caa8c76 },
    .{ 0x8b0a3218, 0x8dab3d23, 0xc3ce1a08, 0x082191ee },
    .{ 0xd063af05, 0x5089f895, 0x6c2eea07, 0xbb92f211 },
    .{ 0x95fce600, 0x594e8bc8, 0xf8086438, 0x5d41da6d },
    .{ 0x2758b31f, 0x423cabda, 0x3c00bafb, 0x2eba31c5 },
    .{ 0xfe33998b, 0x9b35956c, 0xe86d79fc, 0x491c9b0f },
    .{ 0x4826cdf1, 0xb1c13070, 0x7c01c66d, 0x9b4ef227 },
    .{ 0x1ca49203, 0xe408cc44, 0x4f567243, 0x445b06e2 },
    .{ 0x83b3f567, 0x38d66dac, 0x4c587fb9, 0x76393595 },
    .{ 0x9bf49f13, 0xac5751a3, 0x5b05ff7c, 0x2b203af6 },
    .{ 0xead18f15, 0x2b5973e4, 0x6b0d97f1, 0x9c1327ef },
    .{ 0xa00db574, 0x46d8825c, 0x720c166e, 0x6286c098 },
    .{ 0x66291fe6, 0x2a506315, 0x7318d43c, 0xdff4aa3f },
    .{ 0x7819aa1a, 0x2052bf71, 0x0c897060, 0xd67998b6 },
    .{ 0x5ea84c88, 0xe766ad1d, 0xf3326fca, 0xb35bb1cb },
    .{ 0xf75d62dc, 0xa7f6a15e, 0x7f8ecb94, 0x03edcdce },
    .{ 0x4742913d, 0x81f88ab4, 0x0885c509, 0x22026651 },
    .{ 0xfa14ed5a, 0xf2cb4604, 0x262d3cb3, 0xfd1c04af },
    .{ 0xb372d30e, 0x5d9bdd6f, 0x125e2ae5, 0x3f27ef9f },
    .{ 0xec0f142b, 0xff50e7e8, 0x2806916b, 0xf17a234d },
    .{ 0xc41bcf1d, 0x10c2f973, 0x54be6526, 0xaab2df58 },
    .{ 0xcd6710f8, 0xc79b6ed5, 0xc580b110, 0x9201aec0 },
    .{ 0xd3ee37f5, 0x1c5e28c9, 0x6945c8a5, 0xaf04447c },
    .{ 0xddbe96d3, 0x92a5cc5a, 0x87db4012, 0x833210a7 },
    .{ 0xb9381d9f, 0xef4f3a55, 0x36a08049, 0xd519f438 },
    .{ 0xc28969a3, 0xe63a0824, 0x40cb60a6, 0x41527bc3 },
    .{ 0x823b91a7, 0x861db182, 0x8c55c2b3, 0x3e0bed69 },
    .{ 0xc182c005, 0xef95f1dc, 0xe6a7f101, 0xa6ac8dfc },
    .{ 0x5ce31dbe, 0x3630fa4d, 0xa4713f2a, 0xc6280463 },
    .{ 0x190f29e3, 0xc5144029, 0x971c3086, 0xea78d82f },
    .{ 0x41d03b2a, 0xb56c9cb7, 0x61710281, 0xa6a9aa70 },
    .{ 0x01156f25, 0xc85d5822, 0xc616c08d, 0x9f6a4078 },
    .{ 0x91502fc6, 0xb54f4319, 0xe4e82da9, 0xea31fae6 },
    .{ 0xad63348b, 0x1c681cca, 0xfa83203f, 0xcc487821 },
    .{ 0xc78ac5eb, 0xa2f53bd7, 0x45c42a13, 0x9fcacb51 },
    .{ 0x7afe07fa, 0x2acd21e9, 0x8086578f, 0x70c1926a },
    .{ 0x0f912866, 0x775a8c3d, 0x3656afd3, 0x4ec158c8 },
    .{ 0x1fdc8579, 0x52147ae0, 0x67e170ea, 0xa711a433 },
    .{ 0xcf4d63c9, 0xfb90897c, 0xf44fa4c1, 0x73f39ffb },
    .{ 0x597d5d77, 0x66b5f4e4, 0x0c7f72d3, 0xced1d279 },
    .{ 0x25d144f9, 0xfcb2a19a, 0xa6cb11a9, 0x1b7beb58 },
    .{ 0x076db321, 0x2ae34d51, 0x08688c2a, 0x945740b1 },
    .{ 0xf91d3306, 0x43829eb2, 0xe5c07318, 0xd75fc2b6 },
    .{ 0x85ee0eb1, 0x6874c80a, 0x87f9a7fd, 0x14c2b7f4 },
    .{ 0x2abc3724, 0xccb8ecea, 0x12820820, 0x4f597cc6 },
    .{ 0x325670d2, 0x3e06142f, 0xf83425a6, 0xb85b5fbf },
    .{ 0xe21c676a, 0x6e08d554, 0xfa28e4fd, 0xc37669b3 },
    .{ 0x97d9b9c3, 0x54ba182d, 0x1ace9c1a, 0xe58c9db6 },
    .{ 0x6aafd709, 0xdbdd7afd, 0x68eacfe8, 0x64b00bbb },
    .{ 0xd6d180b5, 0x1fbd2ea8, 0x7a56f6f4, 0x687b871f },
    .{ 0x575446bc, 0x5df26d6d, 0x5e0102a9, 0x99c3ba14 },
    .{ 0x5084c312, 0xf9291039, 0xc1710370, 0x01895ee2 },
    .{ 0x035a5488, 0xd344b1a7, 0xa7a0f765, 0x196a1d84 },
    .{ 0xbc178efc, 0xf751cf54, 0x21b33996, 0x7751ad07 },
    .{ 0xd48d7840, 0xd738c266, 0x16386443, 0xc627bcb0 },
    .{ 0x4c9e2e8e, 0xe1dea3fd, 0x350032b4, 0xf2c245f1 },
    .{ 0xbbfda67d, 0x87ce0350, 0x8f3a1ca9, 0x089d40ad },
    .{ 0x885bf635, 0x22d31f49, 0x55859e19, 0x6bc0a4f1 },
    .{ 0x046aa628, 0x24d1b177, 0x9affc047, 0xf9561ad2 },
    .{ 0x39364b5d, 0x18bcbe9a, 0x78c16c62, 0x31642388 },
    .{ 0x7386dafd, 0x643a6e95, 0x76c7d8a3, 0xa91afd4f },
    .{ 0x0df44806, 0xaf7f865e, 0xc3d3849b, 0x27ecbce5 },
    .{ 0xf727a6c7, 0xe8ac9fb4, 0xbad07e04, 0x0dbcd9ae },
    .{ 0x2f17f5f1, 0xcc660304, 0x3a09e56b, 0x863f99fe },
    .{ 0xf4af018f, 0x3d8ef4e8, 0x7bf237ad, 0xa867d34c },
    .{ 0xbc3c74e4, 0x5d9150e2, 0x38f5c306, 0x0abc9813 },
    .{ 0x1afcb0ca, 0x318ce736, 0xccc4d348, 0x141561f7 },
    .{ 0x38a6fa0a, 0x7574cf2b, 0x6767d313, 0x0de772f3 },
    .{ 0xef227ca9, 0x32315374, 0x042da5a8, 0xcbaeb4d7 },
    .{ 0x20c1e57e, 0x4246836e, 0x1cfd2dfa, 0x766add5f },
    .{ 0x17f61af2, 0xe109e2cd, 0x108146e7, 0xbb7ead4c },
    .{ 0x8c195165, 0xe30c60e0, 0xc3a86409, 0x14024420 },
    .{ 0x57fd158e, 0xd61da5d7, 0x3fffdba2, 0x2b79a413 },
    .{ 0x429356ce, 0x9e77bafe, 0xa24181ca, 0x3f2ef757 },
    .{ 0x862abd83, 0xc956c4ac, 0xc7ea5be3, 0xdacd6cbe },
    .{ 0xd781e99d, 0xa0a64db1, 0x52081e5b, 0x3dfd788d },
    .{ 0x1a2196d0, 0x31d1b1f4, 0x8a79380a, 0xdc19aeda },
    .{ 0x4943efde, 0x563698ce, 0xf1feb134, 0xdddd55d6 },
    .{ 0x9f40c9e9, 0xc8762baf, 0xa635bca9, 0x815f027f },
    .{ 0xde025ff6, 0x0cf8837a, 0xc11fe801, 0xa6233393 },
    .{ 0x2969ccc5, 0xdbe98d06, 0x16b46cce, 0xa7513775 },
    .{ 0xb8b03d89, 0xe2489fea, 0x37fb0cfe, 0xfca9dc2d },
    .{ 0xe6735a38, 0xf2097f04, 0xd65b797c, 0xa7eadc7f },
    .{ 0x4989a342, 0x25da1103, 0xc8855b3f, 0xac4c978b },
    .{ 0xdc3d096a, 0x21af9296, 0xd9976333, 0xad9dc0c1 },
    .{ 0x4003c2cc, 0xb2a4266d, 0x9b7d0acb, 0x18832ee9 },
    .{ 0xa47539d6, 0xec4bc7ae, 0x3fd2f991, 0x6e297f43 },
    .{ 0xe8a76873, 0x70eb83bc, 0x787b20e8, 0xe04cd398 },
    .{ 0xb2ae3530, 0x7577a326, 0x2efc8529, 0x870d4cdd },
    .{ 0x4e2b1862, 0x9a83ebab, 0x6b965c65, 0xb9c579de },
    .{ 0xa2e327af, 0x5dc46a06, 0x694dee4d, 0x8810ca7f },
    .{ 0x77f2a50c, 0x149d1dca, 0x628494d4, 0x707d400d },
    .{ 0x95158c41, 0xe7f0761d, 0xc5c63754, 0x6cda8829 },
    .{ 0xe50a8119, 0xbf9aa317, 0x52130b8f, 0x281cae83 },
    .{ 0x7551d66f, 0x169649d1, 0x05a41a3d, 0xa8b323f4 },
    .{ 0x229c44d2, 0xe0ca33ba, 0xd60d641c, 0xe29634da },
    .{ 0x165c1aba, 0x43fccc6a, 0x0743f301, 0x24ec7d75 },
    .{ 0x99c87e5e, 0xb8b0cadb, 0x0290c4d3, 0x0c69c348 },
    .{ 0x07e177b5, 0xa331e9a0, 0x2b6a27ee, 0xd27d6d21 },
    .{ 0x8616b43f, 0x14058503, 0x567af51f, 0x7fef3924 },
    .{ 0x9c2d06a3, 0xc8ea4e9e, 0x826c0c8d, 0xf856e2f6 },
    .{ 0x3724c480, 0x506989ac, 0x03645305, 0x7111e2be },
    .{ 0x9e769d11, 0xd0bd2c19, 0xb1e383a6, 0x17987a71 },
    .{ 0x1dfe00b0, 0xaa7a92f8, 0xf84b3955, 0xf7e92144 },
    .{ 0xf87c7c24, 0x955340c3, 0xf74eac7d, 0x10e3ebf4 },
    .{ 0xca635011, 0x92de7b8c, 0xc734760d, 0xac991b3f },
    .{ 0x9d327f0b, 0x97c43852, 0xd09103d2, 0x316b43fd },
    .{ 0x782c0c6b, 0xb24a296e, 0x4f297d01, 0xf879457a },
    .{ 0xfdfebf18, 0xd095636c, 0x14e75e06, 0x0b47b1e5 },
    .{ 0xe51f8d1a, 0xfdc75163, 0xd45b3208, 0x40340c32 },
    .{ 0x3c0abb3a, 0xe3c2dd8c, 0x5676e963, 0xd0c862cd },
    .{ 0x157d8cef, 0x50b93666, 0x0296f30d, 0x39173fd3 },
    .{ 0x11f772c9, 0x69f3dc02, 0xd43429ba, 0x846cadb1 },
    .{ 0xf734a602, 0x48e80716, 0x82ad6e66, 0x0287c40c },
    .{ 0xeee1d7f7, 0x16de7bc6, 0x4be225b3, 0x35f935d1 },
    .{ 0x24dab416, 0xf6afec1b, 0x39e5f2cc, 0xf2f090e6 },
    .{ 0x910c8b09, 0x340c1064, 0xee139afe, 0x9d177dc0 },
    .{ 0x48e9099b, 0x14c87ff5, 0xdd530fb9, 0xcc1017a7 },
    .{ 0x9ee7b1a0, 0xc8cfca3e, 0x41a59e32, 0xc8987c6a },
    .{ 0xd481ed91, 0xdb6aa1ab, 0x5efb56c2, 0xfb6cc2bd },
    .{ 0xf5f368e8, 0x22e8f09e, 0x5255641d, 0xa80cce15 },
    .{ 0xd5b114ce, 0x2ab987e8, 0x528b8ad8, 0xa8ad93e1 },
    .{ 0x57fb4606, 0x9384511d, 0xfc46779d, 0xd71039f3 },
    .{ 0x795abe7c, 0x3d9ce0a5, 0x436bc1d3, 0x7ee71bd5 },
    .{ 0xab2b8761, 0x987a72e9, 0x9727a4d2, 0xf7370556 },
    .{ 0x04b93d70, 0x9bfcbbdf, 0x63852ff3, 0xd32aa91c },
    .{ 0x5324fa82, 0x416bb23b, 0x95e61697, 0xd8b7df99 },
    .{ 0xf1687fac, 0xc1dab02e, 0x8f996270, 0x6f420245 },
    .{ 0x9d9af9be, 0xc65608cd, 0x3af52825, 0x30dbd1ca },
    .{ 0xb24eee64, 0x5d2962f0, 0x77552651, 0xc7c9ea8f },
    .{ 0x72af6a0e, 0x628cbb5e, 0x510ddabf, 0x6e27c818 },
    .{ 0x88241156, 0xc38bbaef, 0x86706e81, 0x9d333eb1 },
    .{ 0x35bd22f6, 0x71721cb9, 0x5e52ef1f, 0xd7d45738 },
    .{ 0x510e17d6, 0xf871d42a, 0x5eddb793, 0x37375fc0 },
    .{ 0xe339eb6f, 0x52491654, 0x623d0478, 0x693d1266 },
    .{ 0x40ea15dd, 0xddfa39f5, 0xf6c4fd16, 0x5fdf3470 },
    .{ 0x9e039543, 0x5fd73d45, 0x3e7f7d3c, 0xccd0ecd0 },
    .{ 0x7eb9654a, 0x387fe0c4, 0x10da4b76, 0x4ab37bdf },
    .{ 0x007f94ab, 0x0bd5d628, 0x5dfc0c6d, 0x9437321a },
    .{ 0x2861846f, 0xc088de88, 0x42e65ec7, 0x73fe9da8 },
    .{ 0x14d70701, 0xc1b9a9ef, 0x5265eceb, 0x17335078 },
    .{ 0xe005a46a, 0xb9fbac2b, 0x05bd1e16, 0xdb442f4d },
    .{ 0x941f8f98, 0x51deeab3, 0xf5463d8b, 0xc251592b },
    .{ 0x55df8ffd, 0x18b94d68, 0x306aa7db, 0xe300175d },
    .{ 0x5c0b6c68, 0xc5a506bb, 0x0bbbc2b9, 0x411ac8d1 },
    .{ 0x7ede35f0, 0x7661b2c6, 0xc95a199a, 0x7e932e11 },
    .{ 0x1a63a985, 0x42bc0746, 0x74de018b, 0x2d6af399 },
    .{ 0xd5df5117, 0xe02cf3c8, 0xe834faf1, 0xb0147230 },
    .{ 0x9522d966, 0xadab9e0e, 0x2a268508, 0x4d030695 },
    .{ 0xd42822b1, 0x6d097fa8, 0xc73c6cb8, 0xd1d01003 },
    .{ 0xd6c55632, 0xa32145e4, 0x4e464671, 0xf6c4fc90 },
    .{ 0xbfe47900, 0xdd97117d, 0xc073cb23, 0xcd1bd2c9 },
    .{ 0x3855132f, 0x6d583db8, 0x6712fd95, 0x51c66856 },
    .{ 0xaa75fa54, 0xbdc43fd6, 0xa27f1cfa, 0xb612c316 },
    .{ 0xa0c43496, 0xdccb2652, 0xa2bcdf8a, 0x60490ac7 },
    .{ 0x91718806, 0xf004047b, 0x17448291, 0xac266e44 },
    .{ 0xdb15a3cc, 0x053a4ffb, 0xccbe0307, 0x0f1c1869 },
    .{ 0x415b9d76, 0x235ff2c0, 0xdf8c7bef, 0xd313a669 },
    .{ 0x74f8238d, 0xc48d2a8c, 0xcd8faf51, 0x3b50877b },
    .{ 0x1dd0a631, 0xf038afe3, 0x2b46f8f0, 0x3b4ce3c9 },
    .{ 0x8f96fd59, 0x80a0f8a8, 0x36b8aa78, 0xb8d2caa4 },
    .{ 0xb34696e7, 0x3b3c4378, 0xd9a8682e, 0x947ad55c },
    .{ 0xb295964e, 0x12f0329b, 0x4d7f420f, 0x28c065d5 },
    .{ 0x44a82b91, 0x1ae3a731, 0xd8b7d963, 0x2a3b6845 },
    .{ 0x778084dd, 0x4c59f441, 0x2cf13e7a, 0x232322a8 },
    .{ 0x8d1bb6e8, 0xc9868e57, 0x527d74eb, 0x28231f22 },
    .{ 0xd4c779f2, 0x3ab0ad32, 0x9a7cd6a5, 0x9d9dad7a },
    .{ 0x67e7a84a, 0xf1e6e821, 0xc7dcbe26, 0xd27d08fc },
    .{ 0xdedfe431, 0x2de19531, 0x313fa91f, 0x342e36d6 },
    .{ 0xc7d28be7, 0x5516e29b, 0x881d0abe, 0x284d8b52 },
    .{ 0x3d9ac30f, 0x322cb86a, 0xb9e6c9bd, 0x5b590600 },
    .{ 0x8a52ee31, 0x9873e05f, 0xcbbbb9b3, 0xba8d27a9 },
    .{ 0xa23b57dc, 0x955a4034, 0xd6cecfa3, 0x16fe93e0 },
    .{ 0x81b2534d, 0x59f0f7c5, 0xf0b20388, 0x20f11f24 },
    .{ 0x1cb86f34, 0x1e145922, 0xb0247619, 0x13f8ad2e },
    .{ 0x4672267d, 0xca96fc58, 0xe50bf964, 0x8ef05596 },
    .{ 0x6c634fe9, 0x0b377d88, 0xf76d9a47, 0xef666c2e },
    .{ 0x59bdc25f, 0xbaad3cfb, 0xa179e0c8, 0x1ea24fee },
    .{ 0xaf0285f9, 0x700cf4ba, 0x163fbf30, 0x77466f72 },
    .{ 0x75c1d375, 0xb49d23e6, 0x7490242b, 0x5aa75088 },
    .{ 0x995d6af8, 0x260dee37, 0x26b58736, 0xa99d4111 },
    .{ 0xa5f932b2, 0x6f09bbb7, 0x34294e8e, 0x886afaa0 },
    .{ 0xfe002180, 0x7203782f, 0xdecb5407, 0x882ad070 },
    .{ 0xc7dec049, 0x7416a497, 0x69579cda, 0xc40672aa },
    .{ 0x584e50a1, 0x74895a98, 0x788c064a, 0xbfb37e3a },
    .{ 0x8b7c8f16, 0x35d38144, 0xe8c060dc, 0xd4e928e0 },
    .{ 0x5cc40ef9, 0x7d3513ac, 0x1a278c9b, 0x30a77151 },
    .{ 0x9e89fcf1, 0xf4388297, 0x6242c955, 0x4c24b884 },
    .{ 0xa613bbd2, 0x95a9bfd7, 0xf0fafd6f, 0xf5f80915 },
};

comptime {
    std.debug.assert(SEEDS.len == 256);
}

/// Turn relative to the current direction: never a reversal, so this never
/// trips queueDir's 180 guard and never needs to filter anything out —
/// every draw is legal input by construction.
const Turn = enum(u2) { straight, left, right };

const LEFT_OF = [4]canon.Dir{ .left, .right, .down, .up }; // indexed by current dir
const RIGHT_OF = [4]canon.Dir{ .right, .left, .up, .down };

fn turnedDir(cur: canon.Dir, t: Turn) canon.Dir {
    return switch (t) {
        .straight => cur,
        .left => LEFT_OF[@intFromEnum(cur)],
        .right => RIGHT_OF[@intFromEnum(cur)],
    };
}

/// Deterministic per-tick turn generator: an auxiliary xoshiro128** stream,
/// seeded from the seed under test XORed with a caller-supplied salt so
/// distinct players/purposes never draw from the same stream as the
/// simulation's own shared RNG. This is a test-input generator, not part of
/// the simulation.
fn auxRng(seed: [4]u32, salt: [4]u32) rng.Rng {
    var s = seed;
    for (0..4) |i| s[i] ^= salt[i];
    if (s[0] == 0 and s[1] == 0 and s[2] == 0 and s[3] == 0) s[0] = 1;
    return rng.Rng.init(s);
}

fn nextTurn(r: *rng.Rng) Turn {
    return @enumFromInt(@as(u2, @intCast(r.boundedDraw(3))));
}

// --- invariants 1-5: single-player, driving core/world.zig directly -------

fn driveSingle(seed: [4]u32, buf: []canon.Cell) world.World {
    var w: world.World = undefined;
    world.initWorld(&w, buf, COLS, ROWS, false, seed, .playing);

    var turns = auxRng(seed, .{ 0x9E3779B1, 0x85EBCA77, 0xC2B2AE3D, 0x27D4EB2F });
    var tick: u32 = 0;
    while (tick < TICKS and w.status == .playing) : (tick += 1) {
        world.queueDir(&w, turnedDir(w.dir, nextTurn(&turns)));
        world.advance(&w);
        checkStructuralInvariants(&w);
    }
    return w;
}

/// Invariants 1-3, checked after every tick (not just the final one) so a
/// regression is caught at the first tick it appears, not masked by a later
/// tick coincidentally restoring the property.
fn checkStructuralInvariants(w: *world.World) void {
    // #1: body_len == 3 + score/10 (grows by exactly one cell per 10-point eat).
    std.debug.assert(w.cells_len == 3 + w.score / 10);

    const live = world.cells(w);

    // #2: no duplicate body cells.
    for (0..live.len) |i| {
        for (i + 1..live.len) |j| {
            std.debug.assert(!(live[i].x == live[j].x and live[i].y == live[j].y));
        }
    }

    // #3: food never placed on a body cell.
    if (w.food) |f| {
        for (live) |c| {
            std.debug.assert(!(c.x == f.x and c.y == f.y));
        }
    }
}

/// `players_buf` must outlive the returned State — it borrows `players_buf[0..1]`
/// rather than allocating (this module has no allocator), so the caller owns
/// the storage, not a function-local temporary that would dangle on return.
fn stateOf(w: *const world.World, players_buf: *[1]canon.Player) canon.State {
    players_buf[0] = .{
        .status = w.status,
        .dir = w.dir,
        .next_dir = w.next_dir,
        .score = w.score,
        .cells = world.cells(w),
    };
    return .{
        .cols = w.cols,
        .rows = w.rows,
        .wrap = w.wrap,
        .tick = w.tick,
        .rng_state = w.rng.state(),
        .food = w.food,
        .players = players_buf,
    };
}

test "body_len == 3 + score/10 for all 256 seeds" {
    var buf: [COLS * ROWS]canon.Cell = undefined;
    for (SEEDS) |seed| {
        const w = driveSingle(seed, &buf);
        try std.testing.expectEqual(3 + w.score / 10, w.cells_len);
    }
}

test "no duplicate body cells for all 256 seeds" {
    var buf: [COLS * ROWS]canon.Cell = undefined;
    for (SEEDS) |seed| {
        const w = driveSingle(seed, &buf);
        const live = world.cells(&w);
        for (0..live.len) |i| {
            for (i + 1..live.len) |j| {
                try std.testing.expect(!(live[i].x == live[j].x and live[i].y == live[j].y));
            }
        }
    }
}

test "food never placed on a body cell for all 256 seeds" {
    var buf: [COLS * ROWS]canon.Cell = undefined;
    for (SEEDS) |seed| {
        const w = driveSingle(seed, &buf);
        if (w.food) |f| {
            for (world.cells(&w)) |c| {
                try std.testing.expect(!(c.x == f.x and c.y == f.y));
            }
        }
    }
}

test "serialize then deserialize is the identity for all 256 seeds" {
    var buf: [COLS * ROWS]canon.Cell = undefined;
    for (SEEDS) |seed| {
        const w = driveSingle(seed, &buf);
        var players_in: [1]canon.Player = undefined;
        const state = stateOf(&w, &players_in);

        var enc: [canon.HEADER_BYTES + canon.PLAYER_FIXED_BYTES + 4 * COLS * ROWS + canon.CHECKSUM_BYTES]u8 = undefined;
        const rec = try canon.encode(state, &enc);

        var players: [1]canon.Player = undefined;
        var cells_out: [COLS * ROWS]canon.Cell = undefined;
        const decoded = try canon.decode(rec, &players, &cells_out);

        var enc2: [enc.len]u8 = undefined;
        const rec2 = try canon.encode(decoded, &enc2);
        try std.testing.expectEqualSlices(u8, rec, rec2);
    }
}

test "checksum is stable across a serialize/deserialize round trip for all 256 seeds" {
    var buf: [COLS * ROWS]canon.Cell = undefined;
    for (SEEDS) |seed| {
        const w = driveSingle(seed, &buf);
        var players_in: [1]canon.Player = undefined;
        const state = stateOf(&w, &players_in);

        var enc: [canon.HEADER_BYTES + canon.PLAYER_FIXED_BYTES + 4 * COLS * ROWS + canon.CHECKSUM_BYTES]u8 = undefined;
        const rec = try canon.encode(state, &enc);
        const before = canon.checksum(rec);
        try std.testing.expect(canon.verify(rec));

        var players: [1]canon.Player = undefined;
        var cells_out: [COLS * ROWS]canon.Cell = undefined;
        const decoded = try canon.decode(rec, &players, &cells_out);

        var enc2: [enc.len]u8 = undefined;
        const rec2 = try canon.encode(decoded, &enc2);
        try std.testing.expectEqual(before, canon.checksum(rec2));
    }
}

// --- invariant 6: permuted multiplayer input-application order ------------
// A minimal, private, non-ABI two-player step primitive — NOT core/world.zig
// and NOT ns_step (that name is reserved for TASK-023/TASK-053's real C-ABI
// lockstep primitive). See backlog/decisions/decision-020 for exact scope:
// two players share board dimensions, one global food cell, and one RNG
// stream, resolved in ascending player index order (docs/abi-decisions.md
// freeze #1, docs/rng.md "Food placement" point 3); cross-player body
// collision is deliberately not modeled.

const MULTI_PLAYERS = 2;

const MultiPlayer = struct {
    status: canon.Status,
    dir: canon.Dir,
    next_dir: canon.Dir,
    score: u32,
    cells_buf: []canon.Cell,
    cells_len: u32,
};

fn multiOccupied(players: *const [MULTI_PLAYERS]MultiPlayer, x: u16, y: u16) bool {
    for (players) |p| {
        if (p.status == .dead) continue;
        for (p.cells_buf[0..p.cells_len]) |c| {
            if (c.x == x and c.y == y) return true;
        }
    }
    return false;
}

/// Row-major free-cell draw across every live player's body (docs/rng.md
/// "Food placement" #1-2, extended to "any player's body" since food is a
/// single global cell here, same as docs/canonical-state.md).
fn placeFoodShared(cols: u16, rows: u16, players: *const [MULTI_PLAYERS]MultiPlayer, food: *?canon.Cell, r: *rng.Rng) void {
    var occupied_count: u32 = 0;
    for (players) |p| {
        if (p.status != .dead) occupied_count += p.cells_len;
    }
    const total = @as(u32, cols) * @as(u32, rows);
    const free = total - occupied_count;
    if (free == 0) {
        food.* = null;
        return;
    }
    const idx = r.boundedDraw(free);
    var seen: u32 = 0;
    for (0..rows) |y| {
        for (0..cols) |x| {
            if (multiOccupied(players, @intCast(x), @intCast(y))) continue;
            if (seen == idx) {
                food.* = .{ .x = @intCast(x), .y = @intCast(y) };
                return;
            }
            seen += 1;
        }
    }
    unreachable;
}

/// One shared tick, in two phases so that `order` (the permutation under
/// test) can only ever affect phase 1: dir commit + move + wall/self
/// collision, computed per player against the tick's *starting* food value,
/// mutating nothing shared. Phase 2 — body mutation, food consumption, and
/// the one shared-RNG food replacement draw — always runs in fixed
/// ascending player index order, never `order`, which is what makes the
/// permutation provably unable to change the result.
fn stepTick(
    cols: u16,
    rows: u16,
    players: *[MULTI_PLAYERS]MultiPlayer,
    dirs: [MULTI_PLAYERS]canon.Dir,
    food: *?canon.Cell,
    r: *rng.Rng,
    order: [MULTI_PLAYERS]usize,
) void {
    var died: [MULTI_PLAYERS]bool = .{ false, false };
    var new_head: [MULTI_PLAYERS]canon.Cell = undefined;
    var would_eat: [MULTI_PLAYERS]bool = .{ false, false };

    // Phase 1 (order under test): read-only against `food.*`, no shared mutation.
    for (order) |i| {
        var p = &players[i];
        if (p.status == .dead) {
            died[i] = true;
            continue;
        }
        p.dir = dirs[i];
        p.next_dir = dirs[i];

        const head = p.cells_buf[0];
        const v = world.DIR_VEC[@intFromEnum(p.dir)];
        const nx: i32 = @as(i32, head.x) + @as(i32, v.dx);
        const ny: i32 = @as(i32, head.y) + @as(i32, v.dy);
        if (nx < 0 or ny < 0 or nx >= @as(i32, cols) or ny >= @as(i32, rows)) {
            died[i] = true;
            continue;
        }
        const nc = canon.Cell{ .x = @intCast(nx), .y = @intCast(ny) };
        const eating = food.* != null and nc.x == food.*.?.x and nc.y == food.*.?.y;
        const check_len: u32 = if (eating) p.cells_len else p.cells_len - 1;
        var self_hit = false;
        for (0..check_len) |k| {
            if (p.cells_buf[k].x == nc.x and p.cells_buf[k].y == nc.y) {
                self_hit = true;
                break;
            }
        }
        if (self_hit) {
            died[i] = true;
            continue;
        }
        new_head[i] = nc;
        would_eat[i] = eating;
    }

    // Phase 2 (fixed ascending index, never `order`): mutate bodies, resolve
    // shared food, draw the one shared-RNG replacement if anything was eaten.
    var need_new_food = false;
    for (0..MULTI_PLAYERS) |i| {
        var p = &players[i];
        if (died[i]) {
            p.status = .dead;
            continue;
        }
        const confirmed_eat = would_eat[i] and food.* != null;
        const buf = p.cells_buf[0 .. p.cells_len + 1];
        std.mem.copyBackwards(canon.Cell, buf[1..], buf[0..p.cells_len]);
        p.cells_buf[0] = new_head[i];
        if (confirmed_eat) {
            p.cells_len += 1;
            p.score += 10;
            food.* = null;
            need_new_food = true;
        }
    }
    if (need_new_food) placeFoodShared(cols, rows, players, food, r);
}

const MultiResult = struct {
    tick: u32,
    food: ?canon.Cell,
    rng_state: [4]u32,
    players: [MULTI_PLAYERS]MultiPlayer,
};

/// Runs TICKS ticks of the two-player primitive from `seed`, applying
/// per-tick input in `order`. Both players' turn sequences come from the
/// same deterministic per-tick generator regardless of `order` — only the
/// *order in which stepTick visits players within phase 1* varies, which is
/// exactly the "permuted input-application order" AC#2 asks to be explicit
/// about (network input for different players arriving interleaved, not the
/// players choosing different moves).
fn driveMulti(seed: [4]u32, order: [MULTI_PLAYERS]usize, bufs: [MULTI_PLAYERS][]canon.Cell) MultiResult {
    var players: [MULTI_PLAYERS]MultiPlayer = undefined;
    for (0..MULTI_PLAYERS) |i| {
        const cy = ROWS / 2 + @as(u16, @intCast(i)) * 2; // distinct starting rows, off each other's path
        bufs[i][0] = .{ .x = 8, .y = cy };
        bufs[i][1] = .{ .x = 7, .y = cy };
        bufs[i][2] = .{ .x = 6, .y = cy };
        players[i] = .{
            .status = .playing,
            .dir = .right,
            .next_dir = .right,
            .score = 0,
            .cells_buf = bufs[i],
            .cells_len = 3,
        };
    }

    var r = rng.Rng.init(seed);
    var food: ?canon.Cell = null;
    placeFoodShared(COLS, ROWS, &players, &food, &r);

    var turn_streams: [MULTI_PLAYERS]rng.Rng = undefined;
    for (0..MULTI_PLAYERS) |i| {
        turn_streams[i] = auxRng(seed, .{
            0x9E3779B1 *% @as(u32, @intCast(i + 1)),
            0x85EBCA77 *% @as(u32, @intCast(i + 1)),
            0xC2B2AE3D *% @as(u32, @intCast(i + 1)),
            0x27D4EB2F *% @as(u32, @intCast(i + 1)),
        });
    }

    var tick: u32 = 0;
    while (tick < TICKS) : (tick += 1) {
        var any_alive = false;
        for (players) |p| {
            if (p.status != .dead) any_alive = true;
        }
        if (!any_alive) break;

        var dirs: [MULTI_PLAYERS]canon.Dir = undefined;
        for (0..MULTI_PLAYERS) |i| {
            dirs[i] = turnedDir(players[i].dir, nextTurn(&turn_streams[i]));
        }
        stepTick(COLS, ROWS, &players, dirs, &food, &r, order);
    }

    return .{ .tick = tick, .food = food, .rng_state = r.state(), .players = players };
}

fn multiChecksum(result: MultiResult) u64 {
    var players_arr: [MULTI_PLAYERS]canon.Player = undefined;
    for (0..MULTI_PLAYERS) |i| {
        players_arr[i] = .{
            .status = result.players[i].status,
            .dir = result.players[i].dir,
            .next_dir = result.players[i].next_dir,
            .score = result.players[i].score,
            .cells = result.players[i].cells_buf[0..result.players[i].cells_len],
        };
    }
    const state = canon.State{
        .cols = COLS,
        .rows = ROWS,
        .wrap = false,
        .tick = result.tick,
        .rng_state = result.rng_state,
        .food = result.food,
        .players = &players_arr,
    };
    var enc: [canon.HEADER_BYTES + MULTI_PLAYERS * canon.PLAYER_FIXED_BYTES + 4 * COLS * ROWS + canon.CHECKSUM_BYTES]u8 = undefined;
    const rec = canon.encode(state, &enc) catch unreachable;
    return canon.checksum(rec);
}

test "permuted per-tick input-application order yields identical checksums for all 256 seeds" {
    var bufs_a: [MULTI_PLAYERS][COLS * ROWS]canon.Cell = undefined;
    var bufs_b: [MULTI_PLAYERS][COLS * ROWS]canon.Cell = undefined;
    var slices_a: [MULTI_PLAYERS][]canon.Cell = undefined;
    var slices_b: [MULTI_PLAYERS][]canon.Cell = undefined;
    for (0..MULTI_PLAYERS) |i| {
        slices_a[i] = &bufs_a[i];
        slices_b[i] = &bufs_b[i];
    }

    for (SEEDS) |seed| {
        const ascending = driveMulti(seed, .{ 0, 1 }, slices_a);
        const reversed = driveMulti(seed, .{ 1, 0 }, slices_b);
        try std.testing.expectEqual(multiChecksum(ascending), multiChecksum(reversed));
    }
}
